# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo_cliente', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('estado_juridico', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono_fijo', models.CharField(max_length=200)),
                ('telefono_celular', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('ruc', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('estado_juridico', models.CharField(blank=True, max_length=200)),
                ('provincia', models.CharField(blank=True, max_length=200)),
                ('canton', models.CharField(blank=True, max_length=200)),
                ('parroquia', models.CharField(blank=True, max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono_fijo', models.CharField(blank=True, max_length=200)),
                ('telefono_celular', models.CharField(blank=True, max_length=200)),
                ('correo', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('codigo_credito', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('saldo', models.FloatField()),
                ('fecha_concesion', models.CharField(max_length=200)),
                ('fecha_vencimiento', models.CharField(max_length=200)),
                ('tasa_interes', models.CharField(max_length=200)),
                ('tipo_credito', models.CharField(max_length=200)),
                ('numero_cuotas', models.CharField(max_length=200)),
                ('valor_cuota', models.CharField(max_length=200)),
                ('frecuencia_pago', models.CharField(max_length=200)),
                ('entaje', models.CharField(max_length=200)),
                ('ahorro_programado', models.CharField(max_length=200)),
                ('seguro_desgravamen', models.CharField(max_length=200)),
                ('codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cliente')),
                ('ruc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cooperativa')),
            ],
        ),
        migrations.CreateModel(
            name='Garante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=200)),
                ('estado_juridico', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono_fijo', models.CharField(max_length=200)),
                ('telefono_celular', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cliente')),
                ('ruc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cooperativa')),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono_fijo', models.CharField(max_length=200)),
                ('telefono_celular', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('ruc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cooperativa')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa', models.CharField(max_length=200)),
                ('tasa_mora', models.CharField(max_length=200)),
                ('monto', models.CharField(max_length=200)),
                ('forma_pago', models.CharField(max_length=200)),
                ('fecha_pago', models.CharField(max_length=200)),
                ('telefono_celular', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('codigo_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Credito')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='ruc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cooperativa'),
        ),
    ]
