# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0005_auto_20170528_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='saldo',
            new_name='deuda',
        ),
    ]
