# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0008_auto_20170530_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
