# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0009_auto_20170530_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='telefono_celular',
        ),
        migrations.AlterField(
            model_name='garante',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.FloatField(),
        ),
    ]
