# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0010_auto_20170530_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='activo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
