# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0011_credito_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credito',
            old_name='tipo_credito',
            new_name='tipo',
        ),
    ]
