# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0012_auto_20170531_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito',
            name='activo',
        ),
        migrations.AddField(
            model_name='credito',
            name='estado',
            field=models.CharField(default='Activo', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='credito',
            name='encaje',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='credito',
            name='numero_cuotas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='credito',
            name='valor_cuota',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='garante',
            name='cedula',
            field=models.IntegerField(),
        ),
    ]
